version: "3.8"

services:
  database:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: my_backend
    restart: always
    depends_on:
      - database
    environment:
      DB_USER: myuser
      DB_HOST: database
      DB_NAME: mydb
      DB_PASSWORD: mypassword
      DB_PORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"

volumes:
  postgres_data:
